USE bookstore;
select * from books;

truncate table books;
insert into books
(name, description, author, unit_price, quantity)
values 
("War and Peace", 
"A legendary masterpiece, this book is synonymous with difficult reading, so why not challenge yourshelf.",
"Leo Tolstoy", 
21.00, 
9),
("Song of Solomon", 
"One must always read a novel by this Nobel Prize winning author.",
"Toni Morrison", 
16.00, 
8),
("Ulysses", 
"Joyce's parallel use of The Odyssey…has the importance of a scientific discovery... - T. S.Eliot",
"James Joyce", 
17.00, 
10),
("The Shadow of the Wind", 
"An incredible book by a beloved writer is a must read.",
"Carlos Ruiz Zafon", 
30.00, 
5),
("The Lord of the Rings", 
"Most people have seen the epic movie, but have you read the book?",
"J.R.R. Tolkien", 
8.99, 
15),
("The Satanic Verses", 
"Known as one of Salman Rushdie’s greatest works, this book is definitely on the TBR list.",
"Salman Rushdie", 
18.00, 
4),
("Don Quixote", 
"It's no surprise that one of the best books of all time should be read.",
"Miguel de Cervantes", 
30.00, 
9),
("The Golden Compass", 
"Go on an adventure this year with this thrilling fantasy tale.",
"Philip Pullman", 
12.99, 
6),
("Catch-22", 
"If this wasn't already required reading in your school, it's about time you've read it.",
"Joseph Heller", 
28.00, 
5),
("1984", 
"We were pretty certain you've read one of the best books of all time, but in case you haven't, now's your chance.",
"George Orwell", 
17.00, 
20),
("The Kite Runner", 
"The Kite Runner is a 21st century classic. If you've read this brilliant book, read it again.",
"Khaled Hosseini", 
17.00, 
14),
("Little Women", 
"Because you need to know Meg, Beth, Jo, and Amy.",
"Louisa May Alcott", 
11.00, 
15),
("The Cloud Atlas", 
"Another adaptation you’ll want to read to visualize in 2016.",
"David Mitchell", 
23.00, 
11),
("The Fountainhead", 
"A groundbreaking novel that everyone should read at least once.",
"Ayn Rand", 
39.95, 
8),
("The Picture of Dorian Gray", 
"For those who were deprived Oscar Wilde as required reading for school.",
"Oscar Wilde", 
24.00, 
2),
("Lolita", 
"Poignant novels that are also funny are a must-read rarity.",
"Vladimir Nabokov", 
25.00, 
6),
("The Help", 
"This powerful book is beautiful, moving, and hilarious: an essential.",
"Kathryn Stockett", 
17.00, 
23),
("The Liar's Club", 
"The essential American story ... a beauty. — Jonathan Yardley, The Washington Post Book World",
"Mary Karr", 
18.00, 
21),
("Moby-Dick", 
"Either you've read it, or you pretend you've read it.",
"Herman Melville", 
16.00, 
10),
("Gravity's Rainbow", 
"At least one Pynchon novel should be on everyone’s TBR list.",
"Thomas Pynchon", 
23.00, 
7),
("The Handmaid's Tale", 
"Same goes for Margaret Atwood, and The Handmaid’s Tale is definitely a classic.",
"Margaret Atwood", 
15.95, 
9);
